<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0142a693-fe2d-4a25-9d43-a9ea5e1fc7ad</UserSecretsId>
    <Module>Aspire</Module>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiverBooks.Web\RiverBooks.Web.csproj" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.6" />
  </ItemGroup>

</Project>
